In [4]:
from pybaseball import statcast_pitcher, playerid_lookup
player = playerid_lookup('webb','logan')

In [5]:
player

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,webb,logan,657277,webbl001,webblo01,17995,2019.0,2026.0

In [6]:
pitcher_id = player['key_mlbam'].iloc[0]

In [7]:
pitcher_id

np.int64(657277)

In [8]:
data = statcast_pitcher('2024-04-01', '2024-04-30', pitcher_id)

Gathering Player Data

In [11]:
data_full_season = statcast_pitcher('2024-04-01', '2024-09-30', pitcher_id)

Gathering Player Data

In [12]:
data_full_season.shape

(3111, 119)

In [9]:
data.shape

(576, 119)

In [13]:
data_full_season.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,SI,2024-09-24,94.2,-1.09,4.93,"Webb, Logan",572233,657277,field_out,hit_into_play,...,1.0,2.73,1.22,1.22,22.2,-1.011390,19.714922,23.506534,34.839040,22.371164
1,ST,2024-09-24,85.4,-1.42,4.76,"Webb, Logan",572233,657277,NaN,swinging_strike,...,1.0,3.10,-1.39,-1.39,19.7,22.134225,-24.001646,29.198287,48.827880,46.692745
2,SI,2024-09-24,93.8,-1.30,4.85,"Webb, Logan",572233,657277,NaN,ball,...,1.0,2.41,1.45,1.45,20.0,NaN,NaN,NaN,NaN,NaN
3,CH,2024-09-24,87.7,-1.54,4.59,"Webb, Logan",592626,657277,field_out,hit_into_play,...,1.0,3.40,0.58,-0.58,14.2,-7.702721,11.544554,40.539452,40.262069,15.160185
4,SI,2024-09-24,92.9,-1.33,4.81,"Webb, Logan",592626,657277,NaN,called_strike,...,1.0,2.63,1.25,-1.25,20.1,NaN,NaN,NaN,NaN,NaN

In [10]:
data.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,CH,2024-04-30,88.5,-1.11,4.76,"Webb, Logan",677800,657277,triple,hit_into_play,...,1.0,3.06,0.94,-0.94,20.3,16.739926,-16.703502,33.247754,30.873907,39.710444
1,ST,2024-04-30,83.3,-1.39,4.71,"Webb, Logan",677800,657277,NaN,ball,...,1.0,3.33,-1.46,1.46,19.9,NaN,NaN,NaN,NaN,NaN
2,SI,2024-04-30,92.6,-1.00,4.92,"Webb, Logan",641933,657277,strikeout,called_strike,...,1.0,2.45,1.23,1.23,23.9,NaN,NaN,NaN,NaN,NaN
3,CH,2024-04-30,88.6,-1.14,4.71,"Webb, Logan",641933,657277,NaN,foul,...,1.0,3.04,1.16,1.16,17.9,14.409775,-2.250513,36.168207,37.286200,32.824188
4,CH,2024-04-30,88.4,-1.11,4.72,"Webb, Logan",641933,657277,NaN,swinging_strike,...,1.0,3.05,1.16,1.16,20.5,23.186306,-23.565074,35.889765,47.803993,41.331859